# -*- mode: Snakemake -*-
#
# Build customer MIDAS database.
#
# Chunyu Zhao 2019-06-26

import os, subprocess, sys, shutil, gzip
from pathlib import Path
from midas import utility
import Bio.SeqIO
from collections import defaultdict


project_dir = Path("/mnt/chunyu20TB/midas-iggdb/IGGdb/v2.0.0")
toc_fp = str(project_dir/"genomes2species.tab")

mapfile_fp = str(project_dir/"mapfile")

temp_path = Path(str(project_dir/"temp"))
repgenome_path = Path(str(project_dir/"clean_set"))
prokka_dir = Path(str(project_dir/"prokka"))


GENOMES = {}
SPECIES = defaultdict(list)
Gpath = {}
with open(toc_fp) as f:
    next(f)
    for line in f:
        genome_id = line.rstrip('\n').split('\t')[1]
        species_id = line.rstrip('\n').split('\t')[-1]
        GENOMES[genome_id] = str(species_id)
        SPECIES[species_id].append(str(genome_id))
        Gpath[genome_id] = str(project_dir) + "/clean_set/%s" % str(species_id)

with open(mapfile_fp, "w") as out:
    out.write('\t'.join(["genome_id", "species_id", "rep_genome"]) + '\n')
    for genome in GENOMES.keys():
        if GENOMES[genome] == genome:
            line = [genome, GENOMES[genome], 1]
        else:
            line = [genome, GENOMES[genome], 0]
        out.write('\t'.join(map(str, line)) + '\n')

"""
Gene annotation
"""
print(SPECIES.keys()[:10])
rule species_map_genome:
    input:
        str(repgenome_path/"{species}"/"{species}.fna.lz4")
    output:
        str(temp_path/"{species}"/"{species}.fna.lz4")
    params:
        genomes = SPECIES["{species}"]
    run:
        print(input[0])

rule _all_temp:
    input:
        expand(str(temp_path/"{species}"/"{species}.fna.lz4"), species = SPECIES.keys())
