import glob
import os
import shutil
from pathlib import Path
# Chunyu Zhao 2019-06-26


## TODO: read the path from iggdb.py
repgenome_path = Path("/mnt/chunyu20TB/midas-iggdb/IGGdb/v1.0.0/repgenomes_clean")
temp_path = Path("/mnt/chunyu20TB/midas-iggdb/IGGdb/v1.0.0/temp")
prokka_dir = Path("/mnt/chunyu20TB/midas-iggdb/IGGdb/v1.0.0/repgenomes_prokka")

GENOMES = [f.name[:-4] for f in repgenome_path.iterdir() if f.is_file() and f.name.endswith('.fna')]

GENOMES = GENOMES[:10]

rule cleanup_header:
 """Prokka doesn't take | in the header """
 input:
  str(repgenome_path/'{genome}.fna')
 output:
  temp(str(temp_path/'{genome}.fna'))
 shell:
  """
  sed "s/|/_/g" {input} > {output}
  """

rule run_prokka:
 input:
  str(temp_path/'{genome}.fna')
 output:
  faa = str(prokka_dir/'{genome}'/'{genome}.faa'),
  ffn = str(prokka_dir/'{genome}'/'{genome}.ffn'),
  fna = str(prokka_dir/'{genome}'/'{genome}.fna'),
  tsv = str(prokka_dir/'{genome}'/'{genome}.tsv')
 params:
  outdir = str(prokka_dir/'{genome}'),
  prefix = "{genome}"
 shell:
  """
  prokka --kingdom Bacteria --outdir {params.outdir} --prefix {params.prefix} \
         --locustag {params.prefix} --centre X --compliant --force {input}
  """

rule reformat_genome:
 input:
  tsv = str(prokka_dir/'{genome}'/'{genome}.tsv')
 output:
  genes = str(prokka_dir/'{genome}'/'{genome}.genes')
 shell:
  """
  mv {input.tsv} {output.genes}
  """

rule all_prokka:
 input:
  expand(str(prokka_dir/'{genome}'/'{genome}.genes'), genome=GENOMES)
